export const MenuItems = [
  {
    title: "Home",
    url: "/NERTU_Demo",
    icon: "fa-solid fa-house",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Workshop",
    url: "/workshop",
    icon: "fa-solid fa-window-restore",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Project",
    url: "/project",
    icon: "fa-solid fa-address-book",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Publication",
    url: "/publication",
    icon: "fa-solid fa-file-lines",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Staff",
    url: "/staff",
    icon: "fa-solid fa-user",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Gallery",
    url: "/gallery",
    icon: "fa-solid fa-image",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Contact Us",
    url: "/contact",
    icon: "fa-solid fa-envelope",
    cName: "nav-links",
    color: "white",
  },
  {
    title: "Download",
    url: "/download",
    icon: "fa-solid fa-download",
    cName: "nav-links",
    color: "white",
    submenu: [
      { title: "Code", url: "/code", cName: "nav-submenu", color: "white" },
      { title: "Data", url: "/data", cName: "nav-submenu", color: "white" },
    ],
  },
];
